// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// qtreeCPP
Rcpp::List qtreeCPP(arma::mat mypred, arma::vec myresp, double mindev, int mincut, int minsize, double mytau);
RcppExport SEXP qtree_qtreeCPP(SEXP mypredSEXP, SEXP myrespSEXP, SEXP mindevSEXP, SEXP mincutSEXP, SEXP minsizeSEXP, SEXP mytauSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        Rcpp::traits::input_parameter< arma::mat >::type mypred(mypredSEXP );
        Rcpp::traits::input_parameter< arma::vec >::type myresp(myrespSEXP );
        Rcpp::traits::input_parameter< double >::type mindev(mindevSEXP );
        Rcpp::traits::input_parameter< int >::type mincut(mincutSEXP );
        Rcpp::traits::input_parameter< int >::type minsize(minsizeSEXP );
        Rcpp::traits::input_parameter< double >::type mytau(mytauSEXP );
        Rcpp::List __result = qtreeCPP(mypred, myresp, mindev, mincut, minsize, mytau);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
