# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

qtreeCPP <- function(pred, resp, minDev, minCut, minSize, tau) {
    .Call('qtree_qtreeCPP', PACKAGE = 'qtree', pred, resp, minDev, minCut, minSize, tau)
}
